### ISSUE TITLE
File Icons of PowerPoint and Word is not displaying correctly

### ISSUE THREAD

**Issue by vivekkpatel** [homerchen19/github-file-icons#100]
![image](https://user-images.githubusercontent.com/60865708/124374648-cd389f80-dcba-11eb-901f-333a570f96d4.png)

Word icon should be blue and PowerPoint red

**Comment by vivekkpatel** [comment]
I think Gitako has much better icon set Can you use same icons? 
https://github.com/EnixCoda/Gitako

**Comment by csandman** [comment]
There is already a chrome extension for VSCode icons: https://github.com/dderevjanik/github-vscode-icons

However, these colors should be fixed in #121

**Comment by homerchen19** [comment]
Supported in `v1.3.0` 🚀
