### ISSUE TITLE
Icons not showing properly with octotree chrome extension

### ISSUE THREAD

**Issue by withrvr** [homerchen19/github-file-icons#105]
![image](https://user-images.githubusercontent.com/69628500/147602642-cfe9b122-638e-4f10-afd2-56b65552cd9c.png)

y all icons logo  ... of files is not working properly 
with the [octothree chrome extention](https://github.com/ovity/octotree/)

I tried toggling between icons and dark theme of extension
and of github also

but not working

**Comment by wasi-master** [comment]
I mean what do you expect? This extension is for GitHub, not for Octotree. Octotree has it's own custom icon system that requires a premium subscription
