### ISSUE TITLE
Github Pull Request File Tree - Feature request

### ISSUE THREAD

**Issue by nSimonFR** [homerchen19/github-file-icons#107]
Github recently introduced Pull Request File Tree as a preview feature: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/filtering-files-in-a-pull-request%23using-the-file-tree

It would be nice if this extension could provide its functionality to the icons displayed in this tree !

As of right now, it currently looks like this: 

<img width="234" alt="Screenshot 2022-03-08 at 17 44 05" src="https://user-images.githubusercontent.com/13413730/157284591-6571b46d-0d85-431e-9404-791093a68f3c.png">

**Comment by homerchen19** [comment]
Shout out to @acharyarupak391. This feature has been released in `v1.2.0`  🥳
