### ISSUE TITLE
Icon package file-icons-js is very outdated

### ISSUE THREAD

**Issue by csandman** [homerchen19/github-file-icons#120]
The package `file-icons-js` which supplies all of the icons for this package hasn't been updated in a long time, and is missing a lot of the specific file name icons that are currently offered by the `file-icons/atom` package.  Here is an example of what it looks like with this package:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/9214195/175456635-2f834b86-face-4fbb-9528-57e6c6f7cb81.png">

And here is an example using a fork I made which pulls in the newest icons from Atom's file-icons:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/9214195/175456591-7faaac29-9cb8-4e22-a941-d700c2125931.png">

As you can see, it's missing:

- `.prettierrc`
- `.prettierignore`
- `babel.config.js`
- `package-lock.json`
- `tsconfig.json`

And there are many others it is missing for other languages.

I have a local fork I've been working on which has a script to pull in the newest icon fonts and icon database file, and essentially replicates the way `file-icons-js` works except local to the project.  If you'd consider going down that route, I'll make a PR but I want to gauge interest first.

**Comment by homerchen19** [comment]
wow it looks much nicer! I totally agree `file-icons-js` is very outdated. Please feel free to send a PR to fix it

**Comment by shuuji3** [comment]
Thank you, Chris! This is a great update.🙂
