### ISSUE TITLE
Bug in extension for Safari - regex in icondb.js

### ISSUE THREAD

**Issue by christopherpickering** [homerchen19/github-file-icons#123]
Hey,
There is a regex issue in the new build for Safari.

I'm getting an error on this line (2614?) in `content.bundle.js`. 

![image](https://user-images.githubusercontent.com/17788706/176435329-83fd4949-aa1b-4bd1-a987-081661a6e4c2.png)

(I just ran a js formatter on the js so I could see what line was causing the issue)
```js
["tag-icon", ["medium-green", "medium-green"], /(?:\.|^)sha(?:256|sum)?$|(?:\.|^)(?:check|ck|crc(?:32)?|md5|rmd160|sha(?:224|256|384|512|1|2|3)?)?(?:sums?|(?<=\w))$/i, , !1, , /\.text\.checksums$/i],
```

If I comment out this line then everything is working ok. 

@csandman do you have any ideas? Can we just drop that line when doing update assets?

Its coming in from `file-icons/db/icondb.js`.

I'm kinda surprised this isn't popping up in chrome? I'm not sure how to test there.

# To reproduce in Safari:

```bash
npm install
npm run update-assets
npm run build
```

Xcode, open `/safari/File Icons for GitHub and GitLab.xcodeproj`

Change to MacOS:
![image](https://user-images.githubusercontent.com/17788706/176436631-23d9cd42-d719-4b26-a524-4079b9c8c226.png)

- Click run
- Click quite and open in Safari
- Safari > develop > enable unsigned extensions

**Comment by christopherpickering** [comment]
@iRoachie the App Store is publishing a working update w/out that line, they seem to release them around 5pm cst.. so 6 hrs from now 👍🏽

**Comment by csandman** [comment]
I checked this out, it looks like it's breaking because the line includes a positive lookbehind, a feature that [isn't supported in Safari or Firefox](https://stackoverflow.com/a/58460583/11020515).  You can see the warning here: https://regexr.com/6oovg

I can submit a PR to remove this part in the asset updating script.  I'll do it for just this line, if nothing else is broken, but if there is anything else let me know!

**Comment by christopherpickering** [comment]
Thanks for checking it! Since it is not inside a group, would it be safe to just replace the group w/ `\w+`?
```
(?:\.|^)sha(?:256|sum)?$|(?:\.|^)(?:check|ck|crc(?:32)?|md5|rmd160|sha(?:224|256|384|512|1|2|3)?)?(?:sums?|w+)$
```

**Comment by christopherpickering** [comment]
Looks like you already got it covered in your pr :) I'm sure removing it is fine too. It seems like an extremely edgecasy regex.

**Comment by csandman** [comment]
Actually, you're right, I got the purpose of a positive lookahead mixed up for a second.  Positive lookarounds are only really useful when you care about the captured content, where in our case we're just using the RegEx to test another string.  I'm going to tweak my PR to replace any positive lookaheads with their content.

**Comment by christopherpickering** [comment]
@iRoachie Hey, the App Store just released... working for me :)
