### ISSUE TITLE
Missing Icon .txt

### ISSUE THREAD

**Issue by christopherpickering** [homerchen19/github-file-icons#129]
Hi! I found another icon not showing up - a .txt. Something odd or is it really not there? I thought this one would be pretty common.

Thanks!

repo: https://github.com/atlas-bi/Power-BI-ETL

screenshot:
![image](https://user-images.githubusercontent.com/17788706/189857999-27607c27-9de3-4511-adfb-d6decc6cd114.png)

**Comment by Morphclue** [comment]
Isn't this a duplicate of #126?

**Comment by christopherpickering** [comment]
lol yeah... copying myself 😁
