### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by arguiot** [homerchen19/github-file-icons#13]
It would be great 👍 if there were a Safari version of it 😊.

**Comment by xxhomey19** [comment]
Haven't try it yet. I would do it when I'm free. PRs are welcome 😄

**Comment by ptrkcsk** [comment]
I got the extension working in Safari locally with the following steps:

1. [Configure Safari in macOS to Run Unsigned Extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions/running_your_safari_web_extension#3744467)
1. [Convert web extension](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari):
    ```sh
    # In github-file-icons/
    npm run build && xcrun safari-web-extension-converter build
    ```

    This creates and opens an Xcode project
1. Select 'macOS (Extension)' in Xcode sidebar, then choose Product > Run from the menubar. This will open what looks like a desktop version of File Icons for GitHub and GitLab.
1. Click 'Quit and Open Safari Extensions Preferences...'
1. Enable File Icons for GitHub and GitLab

![GitHub File Icons extension running on Safari](https://user-images.githubusercontent.com/4766244/141718115-024a9157-db05-4208-a86d-ff1bd8945d1e.png)

**Comment by christopherpickering** [comment]
Thanks! This still works 👍🏽

**Comment by christopherpickering** [comment]
@ptrkcsk did you find a way to keep the extension after a reboot? I have to read it after a reboot.

**Comment by christopherpickering** [comment]
It seems like to get the extension to be signed you have to fork out the $100 to add it to the appstore/get a developer certificate to sign it. https://stackoverflow.com/questions/39927598/can-you-distribute-a-safari-app-extension-outside-the-mac-app-store

I'm happy to put it on the App Store. Any one interested in contributing to the fees? From browsing other repos it looks like a GitHub action can be setup to build and deploy it to the App Store. https://preece.dev/2020/06/ios-testflight-deploy-with-github-actions/. If I do it, I'd probably make a separate repo that checks here for pushes on master once a day and build a new version where there's been an update.
@homerchen19 what do you think?

**Comment by christopherpickering** [comment]
@ptrkcsk  I took the plunge :D I had to tweak a few files in the extension converter output to make it build a usable package. Let me know if they work for you w/out turning on the unsigned option in Safari.

**Comment by christopherpickering** [comment]
I got a GitHub action to build the extension using my cert, here's a build with the app you can download. After unzipping It needs to go into "applications" before running.

https://github.com/christopherpickering/github-file-icons/actions/runs/2551948841

**Comment by christopherpickering** [comment]
Here's a build in the App Store: https://apps.apple.com/app/file-icons-for-github/id1631366167

**Comment by homerchen19** [comment]
https://github.com/homerchen19/github-file-icons/pull/119
