### ISSUE TITLE
`gulpfile.ts` should have Gulp icon

### ISSUE THREAD

**Issue by gluons** [homerchen19/github-file-icons#47]
`gulpfile.ts` should also have Gulp icon. But it's TypeScript icon now.

![default](https://user-images.githubusercontent.com/4688092/46745902-2759d100-ccd8-11e8-90e4-bfde0e4477ff.png)

---

This issue will be fixed by websemantics/file-icons-js#6

**Comment by xxhomey19** [comment]
Thanks, I'll update the package once they merge your PR and release a new version.

**Comment by gluons** [comment]
I'm personally afraid that `file-icons-js` may be abandoned.  
It hasn't got any updates for year. 🙁

**Comment by xxhomey19** [comment]
Yeah I'm afraid of that as well :(
If you want to fork it and create another package, then perhaps we can move from that library to yours.

**Comment by homerchen19** [comment]
Supported in `v1.3.0` 🚀
